# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OWEsBbw1_dn_xg_jPGVvq-j0qMm850-v
"""

T = int(input('qual é o chá correto?')) 
comp = input('quais ~são as suposições dos competidores?').split()
a = int(comp[0])
b = int(comp[1])
c = int(comp[2])
d = int(comp[3])
e = int(comp[4])
if a == T:
  a = 1
else:
  a = 0
if b == T:
  b = 1
else:
  b = 0
if c == T:
  c = 1
else:
  c = 0
if d == T:
  d = 1
else:
   d = 0
if e == T:
   e = 1
else:
   e = 0
print(a + b + c + d + e)
#finalmente deus