# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uaWHOQVVO5-k5-s4HvoEOyXj6nC3QsdC
"""

import numpy as np
p, n = input('diga a altura do pulo e n de canos: ').split()
p = int(p)*-1
x = list(map(int, input('altura dos canos: ').split()))
arrayx = np.array(x)
arrayxx = np.array(x[1])
sub = np.subtract(arrayx,arrayxx)
subtr = list(sub)

if all(i >= p for i in subtr) == True:
  print('you win')
else:
  print('game over')