# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j2jQIZEJ5L9H4YNma9LC8hzIYIEJtnwZ
"""

D = int(input('qual a distância?'))
if D <= 800:
  print(1)
elif D <= 1400:
  print(2)
else:
  print(3)