# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ku9OEVBPWW37f3huIriK4fozviYyKiHU
"""

c = int(input('quantos competidores tem?'))
p = int(input('quantas folhas tem?'))
f = int(input('quantas folhas são por competidor?'))
total = c*f
if p >= total:
  print('S')
else:
  print('N')