# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GdFEW20MqEijFk_W70tUP583RTIStdfp
"""

DDD = int(input('qual o seu DDD? '))
if DDD == 11:
  print('são paulo')
elif DDD == 55:
  print('santa maria')
elif DDD == 61:
  print('brasilia')
elif DDD == 71:
   print('salvador')
elif DDD == 21:
   print('Rio de Janeiro')
elif DDD == 32:
  print('juiz de fora')
elif DDD == 19:
  print('campinas')
elif DDD == 27:
  print('vitória')
elif DDD == 31:
  print('belo horizonte')
else:
    print('DDD não cadastrado')