# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZQVEazrt0RwHcAzDwgl-wdGky-sqfbGc
"""

b = int(input('quantas bolinhas a amélia tem?'))
g = int(input('quantos galhos a arvore tem?'))
falt = g//2 - b
if b < g//2:
  print('faltam  {} bolinhas, amélia!!!!'.format(falt))
else:
  print('a amélia tem todas as bolinhas!yayyy!')