# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ul66FMxTWOJV3sAN0nB1JSKjZHURXZPQ
"""

idd = int(input('quantos anos você tem (em dias)?'))
anos = idd // 365
meses = (idd%365)//30
dias = (idd%365)%30

print('você possui {} anos, {} meses e {} dias' .format(anos, meses, dias))