# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17vg2PrPqLC40Zs0XweeUxt_3lMTZ8bmH
"""

#Nessa aqui eu pedi ajuda ao chatgpt, pois não tinha conhecimento da função split e não estava conseguindo declarar duas variáveis em uma única linha
from math import sqrt
x1, y1 = input('quais são os valores de x1, y1 (separados por espaço)? ').split()
x2, y2 = input('quais são os valores de x2, y2 (separados por espaço)? ').split()
x1 = float(x1)
y1 = float(y1)
x2 = float(x2)
y2 = float(y2)
dist = sqrt((x2-x1)**2 + (y2-y1)**2)
print('{:.4f}'.format(dist))