# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ul66FMxTWOJV3sAN0nB1JSKjZHURXZPQ
"""

id = int(input('qual o número do funcionário? '))
ht = int(input('quantas horas trabalhadas? '))
vph = float(input('quanto recebe por hora trabalhada? '))
salario = ht*vph
print(' NUMBER = {}' .format(id))
print('SALARY = ${:.2f}' .format(salario))